### PR TITLE
Update sample-type.ttl

### PR DESCRIPTION
**Pull request by geoderekh**
removed hyperspectral scan as this is better modelled as an observation type on a core or cuttings sample type. Happy to present my rationale and evidence of the approved business procedure to a group if needed.

### CODE REVIEW

**Review by Greenwoodmatthew — APPROVED** [review]
I agree that the hyperspectral scan is an observation type and not a sample type.  For Hyperspectral i believe the model is that the core is a sample of the borehole, and the scan is a observation of the core

**Review by LukeHauck — APPROVED** [review]
Tech good. Approved.

**Comment by Greenwoodmatthew** [comment]
Hi all. Checking on status of this.  Ready to merge? @Steven-Bowden do you need to review?

**Comment by geoderekh** [comment]
@Steven-Bowden  I notice that geoproperties PROD still recognises Hyperspectral Scan as a valid sample type. This issue seems to pop up regularly, so can we align the vocab PR-commit-merge procedure with the following steps to update the graph DB and SRA service request to refresh the Geoprops server. I thought that this had been/was going to be automated by Nick.

**Comment by Greenwoodmatthew** [comment]
@Steven-Bowden is there a final step that id missing between committing the cose to mainin github and picking up the new vocabs in prod?  Is this an SRA task, or a GSQ task?

**Comment by Steven-Bowden** [comment]
GSQ task is being resolved as per GSD-480

**Comment by Steven-Bowden** [comment]
resolved https://vocabs.gsq.digital/v/vocab/def:sample-type

**Pull request merged**
