### PR TITLE
Update DES vocabs following AGLDWG review and HTTPS changes

### PR DESCRIPTION
**Pull request by broughd-qld**
Hi @UbuntuScott, @nicholascar and @KellyVance 
I have changed the vocabularies based on the advice for minor naming changes, eg resource-type to resource-types.

I have based the branch on the HTTP to HTTPS branch that is underway to change a lot of the vocabs.

@nicholascar - When this is completed, will look to you to update the IRI at linked.data.gov.au as previously discussed.

### CODE REVIEW

**Comment by nicholascar** [comment]
No problems: standing by to make changes at the redirect end when the content changes are merged. I guess I'll automatically see the notification!

**Review by UbuntuScott — COMMENTED** [review]
@KellyVance  is there a quick way to update all the modified dates on all the files? 
or would you like us to update the DES ones?

**Comment by nicholascar** [comment]
> ...is there a quick way to update all the modified dates on all the files?

I could find/replace all modified dates to set them to today easily enough, if that's what @KellyVance wants. Or any subset of vocabs.

**Comment by broughd-qld** [comment]
I just updated the base branch for this PR. Realised I had it set to Master when it should of been from the HTTPS branch (HTTP -> HTTPS changes) that Nic created.

**Comment by KellyVance** [comment]
Lets do a find and replace on this subset first. At least these vocabularies aren't tied into any of the internal systems here so will be a good test case.

**Review by KellyVance — APPROVED** [review]

**Comment by broughd-qld** [comment]
I have manually updated the update date - did this when switching the base branch - figured it was the easiest way.

**Pull request merged**
