### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by johnmckellar**
GSQ Feature Status for review please.
Paul, can you have a critical look at the various concepts please, especially in relation to the status drop-down for GA's ASUD. Please bear in mind that each status has to be mutually exclusive of the others. I found this to be a problem in dealing with them. And the vocab needs to apply to ALL geologic features, not just lithostratigraphic ones.
Cheers, 
John
PS: Although the list seems simple, I found it to be a little complex and quite problematical. And, the vocab may still need to be kicked around a bit (or more)!!

### CODE REVIEW

**Comment by BlakePaul** [comment]
Hi John,

I am out at Zillmere for the rest of this week.  I will have a look at it next week.

Regards
Paul

**Comment by johnmckellar** [comment]
Thanks Paul. Not a problem. 👍

________________________________

**Comment by KellyVance** [comment]
Hi @johnmckellar . 
This is a tricky one. This to me seems like at least two vocabularies. As you've mentioned in other discussions, getting this to fit logically with the GA statuses requires composite terminology. I imagine that the GA list has grown organically over time to fit the needs of systems with significant human intervention, but without the kind of ontological rigour as we/they would apply if building it in the present. Let's discuss on teams how to best handle this, I have some ideas, but need to bounce them around to see if they make sense.

**Comment by BlakePaul** [comment]
Sorry.  I forgot about this.  The definitions look OK to me and will have a lot of overlap with the Rock Unit Status from MERLIN that will be needed.

**Comment by johnmckellar** [comment]
OK, thanks Paul. I take it that you approve of the definitions and structure. If so, this then leaves it for Vance and Kate to scrutinize the code.

**Comment by johnmckellar** [comment]
Good morning @KellyVance 
Yes, it has been tricky. Do you want to leave it for quick discussion in tomorrow's 9 am GI meeting re the issue and who you want involved (in the Teams discussion)? Or do you wish me to just set the Teams discussion without going through this step? And, either way, who is to involved (in addition to ourselves): Kate and Paul (of course), but anyone else?

**Comment by BlakePaul** [comment]
Hi John,

Yes, I approve them.  I did look for an approve button while making the comment in GitHub but could not find one.

Regards
Paul

**Comment by johnmckellar** [comment]
👍 Thanks Paul. As you could see, I had to use some composite terminology, to make each term exclusive, to embrace GA 's 'non-exclusive' terminology, but, at the same time, apply the rigor needed for the ontology.

Vance thinks the vocab can be split, to overcome the need for composite terms, and we need to toss his ideas around.

Cheers,

John

________________________________

**Comment by BlakePaul** [comment]
Hi John,

I had started looking at vocabs needed for the rock unit but been distracted by other things.  Hopefully I will be back on it before the end of the week.

I had looked at but not started Rock Unit Statuses from MERLIN and been wondering about definitions.  Some will be equivalent with what you have created but I think I need to speak to Ian to know exactly what the difference is between Defined and Fully Described and some of thee others.
[cid:image002.png@01D70F58.3B2491B0]

Regards
Paul Blake

**Comment by KellyVance** [comment]
Request is now stale. To arrange file to be reuploaded for fresh review.

**Pull request closed without merging**
