### PR TITLE
Update georesources-report-types.ttl

### PR DESCRIPTION
**Pull request by KellyVance**
Label change to Coal and Mineral reports "Annual" to "Activity" to align with Mineral Resource Regulation.
Edited AltLabels as necessitated by the above change.
Expanded definitions where applicable to include reference to MRR sections.

Vocabulary caches will need to be refreshed prior to next Development Cycle deployment.

- [x] Tech and system @DavidCrosswellGSQ 

- [x] Content @GSQ-AI or @LizDerrington 

- [x] Product and Vocab Owner @talebib 

FYI @SalEdwards01

### CODE REVIEW

**Review by talebib — APPROVED** [review]

**Comment by LizDerrington** [comment]
Looks good Vance.
Line 303 change 'annual' to 'annually'.
Line 312 "Only applicable to coal 'or' (not 'and') oil shale mining leases..."
Throughout: change all references from Queensland 'Mineral and Resources Regulation 2013' to Queensland 'Mineral Resources Regulation 2013'

**Comment by KellyVance** [comment]
@LizDerrington Thanks Liz, changes made as requested.

**Comment by LizDerrington** [comment]
Thanks Vance, I approve

**Comment by KellyVance** [comment]
@DavidCrosswellGSQ @GSQ-AI @LizDerrington @talebib 
Can i please get a new review on this PR please? A few extra requirements emerged so I have made extra commits.

**Comment by LizDerrington** [comment]
Looks appropriate and I approve.

**Review by talebib — APPROVED** [review]

**Review by DavidCrosswellGSQ — APPROVED** [review]

**Pull request merged**
