### PR TITLE
Add currencies

### PR DESCRIPTION
**Pull request by KellyVance**
Addition of international currencies.
Collections of common/accepted currencies for reporting to be added later.

uat-vocabularies http://linked.data version of file
vocabularies https://linked.data version of file

### CODE REVIEW

**Review by LukeHauck — COMMENTED** [review]
Validator is giving me >> **Unexpected "Currency" on line 1838.**

**Comment by KellyVance** [comment]
@LukeHauck 
Good pick up. Problem between chair and keyboard. had some double " marks in there. should be fixed now.
> Validator is giving me >> **Unexpected "Currency" on line 1838.**

**Comment by LukeHauck** [comment]
SKOS Testing fagged errors >> 
[currencies.txt](https://github.com/geological-survey-of-queensland/vocabularies/files/6957765/currencies.txt)
**anr - Ambiguous Notation References
Finds concepts with multiple or identical notations within the same concept scheme.	
FAIL (179)**

**Comment by KellyVance** [comment]
> SKOS Testing flagged errors >>
> [currencies.txt](https://github.com/geological-survey-of-queensland/vocabularies/files/6957765/currencies.txt)
> **anr - Ambiguous Notation References Finds concepts with multiple or identical notations within the same concept scheme. FAIL (179)**

@LukeHauck that flag one is ok to ignore here. The concepts have a numeric and an alphabetical notation. But each is tagged with which style of notation it belongs to.

**Review by LukeHauck — APPROVED** [review]
All good.

**Review by katewd — APPROVED** [review]
looks good to me

**Pull request merged**
