### PR TITLE
minor tweaks to DES vocabularies for refresh HTTP/HTTPS

### PR DESCRIPTION
**Pull request by broughd-qld**
Tweak of 5 DES vocabularies to see if the HTTP/HTTPS issue can be fixed be reloading.

Also changed the order of `a dqv:Dimension ; a skos:Concept ;` to `a skos:Concept ; a dqv:Dimension ;` in data quality vocabularies.

@KellyVance and @johnmckellar - I don't believe any of these vocabularies are used by GSQ and hopefully they can be updated for DES usage.

cc @UbuntuScott @nicholascar

### CODE REVIEW

**Comment by broughd-qld** [comment]
Just have to tweak Observed Properties to include a few additional values for further testing.

**Comment by broughd-qld** [comment]
@johnmckellar and @KellyVance - If none of the vocabs are used by GSQ are we good to approve and merge - with a push to VocPrez?

**Comment by johnmckellar** [comment]
I'll leave the final OK to Vance.
________________________________

**Review by KellyVance — APPROVED** [review]
Approved.
Sometime in the near future I would like to redo the vocabulary folder structure here to delineate the raw files 'governed' by each group. Ideally with the view to 1 master file per vocabulary but governed by the correct custodian, and with separate vocprez instances that draw from the same coherent and consistent master library but fit-for-purpose for each agency or entity. I will update VocPrez in the next 24 hours.

**Pull request merged**
