### PR TITLE
Removed Geophysics Report Types

### PR DESCRIPTION
**Pull request by CantRoger**
Discussions with David Crosswell and Geophysics Team on 15/6/2020 resulted in agreement these 2 report types will not be lodged via the portal in this way. Instead they can be lodged as an 'associated document' to either a 'Geophysics Final' or other report (discussions ongoing).

### CODE REVIEW

**Comment by CantRoger** [comment]
Keeping the report types in the vocab for now, but removing them from the lodgement portal collection list as advised by Vance.

**Comment by KellyVance** [comment]
@GSQ-AI  is vocab owner for report types

**Comment by CantRoger** [comment]
> @GSQ-AI  is vocab owner for report types

Apologies @GSQ-AI !! You were there yesterday, so you know what this is about.

**Comment by DavidCrosswellGSQ** [comment]
> All good with me. Doesn't break anything as far as I can tell, so if you want it, you got it! Approved!
> 
> At the same time, can we make some changes to line 270 to change "Mine Plan Lodgement" to "Mine Working Plan", based on some input from Genevieve Evans regarding their naming?

@GSQ-AI - can you please check this change with Julie Devine in the Townsville office - as the primary person who processes Mine Plan Lodgements, I expect she will have an opinion on this.

**Pull request merged**
