### PR TITLE
Update observation-detail-type.ttl

### PR DESCRIPTION
**Pull request by KellyVance**
Additions to Observation Details
Processing Date
Software

Hylogger specific notes: 
Scanned date to be recorded as the Observation Date (in main observation table - Date selector)
Hylogger instrument to be input into Observation Instrument (in main observation table - Free text)

@katewd please check content is as discussed.
@LukeHauck please check content and pass through the file validation tools.

### CODE REVIEW

**Review by LukeHauck — APPROVED** [review]
The new concepts read fine and the tech is good. Approved.

**Review by katewd — APPROVED** [review]
looks good.

**Comment by katewd** [comment]
I haven't deleted the branch, in case more changes are needed for this specific topic. Thanks for your quick work on this Vance.

**Comment by KellyVance** [comment]
I'll delete this one. More updates will be needed on the lpx-updates branch. So i'll get this done and updated and resolve any branch conflicts.

**Pull request merged**
