### PR TITLE
Content Review - commodities

### PR DESCRIPTION
**Pull request by KellyVance**
Content review for commodities vocabulary

### CODE REVIEW

**Comment by geoderekh** [comment]
@CourteneyD lets meet early next week and we can discuss the necessary changes :)

**Comment by KellyVance** [comment]
@ derekh
> @CourteneyD lets meet early next week and we can discuss the necessary changes :)

As discussed, this is an alignment to merge the merlin codes and the established CGI vocabulary. It includes _all_ the commodities from MERLIN (with mapping to [CGI](https://vocabs.ands.org.au/viewById/55)) that the Minerals Team provided by email on Tuesday 11 Feb.

Further to that the Minerals Vocabulary, which should include a comprehensive set of minerals, has an [outstanding review request](https://github.com/geological-survey-of-queensland/vocabularies/pull/63) from December 4th 2019

**Comment by geoderekh** [comment]
@KellyVance it seems that something broke as there is a disconnect between many of concept and exactMatch pairs. 
And yes, lets meet up with @CourteneyD and finalise this vocab once and for all.

**Comment by KellyVance** [comment]
@geoderekh @CourteneyD @predam1 @GSQ-AI @DavidCrosswellGSQ 
All, this vocabulary is required by SRA to build the lodgement portal.
Deadline for review is COB Friday 6th March.

**Comment by CourteneyD** [comment]
Approve this vocabulary for 

> @DerekH
> 
> > @CourteneyD lets meet early next week and we can discuss the necessary changes :)
> 
> As discussed, this is an alignment to merge the merlin codes and the established CGI vocabulary. It includes _all_ the commodities from MERLIN (with mapping to [CGI](https://vocabs.ands.org.au/viewById/55)) that the Minerals Team provided by email on Tuesday 11 Feb.
> 
> Further to that: the Minerals Vocabulary, which should include a comprehensive set of minerals, has an [outstanding review request](https://github.com/geological-survey-of-queensland/vocabularies/pull/63) from December 4th 2019

This has been done

**Pull request merged**
