### PR TITLE
Update survey-relationship-type.ttl

### PR DESCRIPTION
**Pull request by LukeHauck**
Update display list

### CODE REVIEW

**Review by Steven-Bowden — APPROVED** [review]
looks good

**Comment by nicholascar** [comment]
If you are going to make more of the Concepts top concepts in the vocab, then you need to remove their `broader` relationship.

For example, you add:

```
cs:
    skos:hasTopConcept
        ...
        srt:infill
        ...
.
```

and yet your definition for `srt:infill` is:

```
srt:infill
    a skos:Concept ;
    skos:historyNote "Developed by the Geological Survey of Queensland." ;
    rdfs:isDefinedBy cs: ;
    skos:broader srt:follow-up ;
    skos:definition "A follow-up survey designed to increase the spatial resolution of a pre-existing survey, usually using the same parameters to ensure data compatibility."@en ;
    skos:inScheme cs: ;
    skos:prefLabel "Infill"@en ;
.
```

Note the `broader` predicate indicating `srt:follow-up`.

So you need to either remove the broader predicates from those Concepts you are now making top concepts - flattening the hierarchy - or leave them in but remove the top concept declarations.

If you want a flat listing of all the Concepts in the vocab, regardless of their position in the Concept Hierarchy, you should add them all to a Collection.

**Review by nicholascar — CHANGES_REQUESTED** [review]
See my previous comment

**Review by Steven-Bowden — CHANGES_REQUESTED** [review]
Thanks for the advice on this one Nick, very helpful. Apologies Luke, it is just the reprocessed-from that needs to be added. The others look to be captured by their broader relationships.

**Comment by LukeHauck** [comment]
I have amended the vocabulary to declare only two Top Concepts, "same-project", and "follow-up".

I have removed the Top Concept declarations from the specific relationship types, and have shuffled them into one of these two Top Concepts using the Broaders.

Top Concept: same-project
	Dependent
	Independent
	
	
Top Concept: follow-up
	Extension
	Infill
	Repeat
	Reprocessing
	Reprocessed-from
	Resampling

**Review by Steven-Bowden — APPROVED** [review]
approved

**Review by GSQ-AI — DISMISSED** [review]
Approved

**Comment by LukeHauck** [comment]
Included the edits from 534 into 527.

**Review by GSQ-AI — APPROVED** [review]
Combining the two PR's into one looks good to me.

**Pull request merged**
