### PR TITLE
Update geologic-feature-types.ttl

### PR DESCRIPTION
**Pull request by johnmckellar**
@nicholascar @edmondchuc 
Corrected/inserted some broader relationships; deleted 'subgroup' which is a rock unit rank .

### CODE REVIEW

**Comment by johnmckellar** [comment]
@mckillopm @BlakePaul 
May I talk you through this PR request, if needs be.
Cheers,
John

**Review by BlakePaul — APPROVED** [review]
Approved

**Review by mckillopm — APPROVED** [review]
Approved

**Comment by johnmckellar** [comment]
Thanks Paul, Mike

**Pull request merged**
