### PR TITLE
For Content Review - Roles 3x

### PR DESCRIPTION
**Pull request by KellyVance**
3 Roles vocabularies from existing standards (VocPrez links below)
[ISO/IEC 111179-6 Roles and Responsibilities ](https://vocabs.test.gsq.digital/vocabulary/RolesAndResponsibilities)
[ISO19115-1 CI_RoleCode Codelist](https://vocabs.test.gsq.digital/vocabulary/RoleCode)
[DataCite Metadata Schema Roles](https://vocabs.test.gsq.digital/vocabulary/dataciteroles)

Custodian - @mark-gordon-dnrme 
Peer Reviewer 1 - @johnkirsten

### CODE REVIEW

**Comment by johnkirsten** [comment]
All good

**Comment by mark-gordon-dnrme** [comment]
@DavidCrosswellGSQ @nicholascar The ISO/EEC Vocab may need some alternate labels to cater for our governance groups and role structures. I also noticed that content authorities and data manager roles are not covered?

**Comment by mark-gordon-dnrme** [comment]
@DavidCrosswellGSQ @nicholascar Sorry - is see some of these roles are in the Vocabulary: ISO19115-1 CI_RoleCode Codelist however there needs to be alt labels and the addition of a data manager role.

**Comment by nicholascar** [comment]
@mark-gordon-dnrme we can’t add roles to these vocabs as we are just copying what’s in the standards (ISO11179 etc.) as-is. For roles that are not covered, the plan is to make our own GSQ roles vocab that both re-uses any roles from these three we like and declares any we think are missing.

**Comment by DavidCrosswellGSQ** [comment]
@mark-gordon-dnrme we are going to create a new vocabulary GSQ ROLES.
This will then match to the concepts in one of the three standard vocabs.
Recommend to approve this review.

**Pull request merged**
