### PR TITLE
http -> https for linked.data.gov.au

### PR DESCRIPTION
**Pull request by nicholascar**
Changing all instances of http://linked.data.gov.au to https://linked.data.gov.au, note the **s**, as per requirements from the Aust Gov Linked Data WG.

This is a one-time change: all use of linked.data.gov.au should be using the HTTPS version going forward, so you will need to update all references to linked.data.gov.au URIs everywhere to HTTPS.

### CODE REVIEW

**Comment by KellyVance** [comment]
Hi Nick,

I assume that should read "Changing all instances of http://linked.data.gov.au to https://linked.data.gov.au". 
I'll review and approve the changes here as soon as a i get a few moments, but I will have to coordinate with the managers of our databases and apps to make sure nothing breaks when I push the changes through into VocPrez and all the dependent systems.

**Comment by nicholascar** [comment]
Hi @KellyVance ooops, amended description!

Yes, this HTTP -> HTTPS is a pain - I have a _lot_ of data to change - but we really have no choice since DTA really don't want to allow us to operate a non-HTTPS domain. Still, it really does look to be a on-time thing since there's no other protocol on offer for this sort of internet function and there hasn't been for 20+ years, so we wont have to go to xxx://linked.data.gov.au.

(it is possible other forms of PIDs could be minted [with distributed ID](https://w3c.github.io/did-core/)...)

Any luck with the VocPrez update? I'm a bit bottle-necked by it now - can't search, the current instance has different system patterns than the new ones (2.0+) so happy to help out with the update as needed.

**Comment by KellyVance** [comment]
Working on getting the vocprez update deployed independently of other work. 

I'll have to work through how the change to https will affect our vocabularies, pids, and various application look-ups.
Obviously a pid should be persistent (clue is in the title), but having a dataset where a portion is http://xxx.xxx/xx/1234 and another portion of https://xxx.xxx/xx/1234 could be even more problematic. Will catch you via email to discuss a little more deeply.

**Comment by broughd-qld** [comment]
@KellyVance - We are planning a go-live for our catalogue in early May. Do you think there is a chance that this PR can be sorted by the end of the month? This will also allow us to update and test the vocab ingestion from VocPrez into our CKAN instance and finish the data migration.

No pressure - just checking. Let me know if there is anything I can do to assist.
cc @UbuntuScott

**Comment by nicholascar** [comment]
> test the vocab ingestion from VocPrez into our CKAN instance

Just note that VocPrez 2.5.5, that you can see in action at http://dawe.surroundaustralia.com, has a simplified vocab content listing for systems like CKAN. Compare the current GSQ VP views of a vocab here:

https://vocabs.gsq.digital/vocabulary/address-type?_profile=alt

with the DAWE VP here:

http://dawe.surroundaustralia.com/object?uri=https%3A//linked.data.gov.au/def/phs/voc/capturing-methods&_profile=alt

The latter has a so-called "Drop-Down List" profile that delivers simple JSON, e.g. http://dawe.surroundaustralia.com/object?uri=https%3A//linked.data.gov.au/def/phs/voc/capturing-methods&_profile=dd&_mediatype=application/json

This flat content listing is likely much easier for devs to integrate into CKAN than having to learn to parse RDF.

Actually, we could add other export formats easily too...

**Comment by broughd-qld** [comment]
Sounds like we implemented something pretty similar to the Drop-Down List profile manually ourselves for CKAN. 

We use a SPARQL query against the service to return what we need and return as JSON. see our example for [Information Security Classification](https://vocabs.gsq.digital/endpoint?query=prefix%20skos%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0Aselect%20*%0Awhere%20%7B%0A%20%20%3Fconcept%20skos%3AprefLabel%20%3FprefLabel%20.%0A%20%20OPTIONAL%20%7B%3Fconcept%20skos%3Adefinition%20%3Fdefinition%20%7D%20.%0A%20%20OPTIONAL%20%7B%3Fconcept%20skos%3Abroader%20%3Fbroader%20%7D%20.%0A%20%20%3Fconcept%20skos%3AinScheme%20%3Chttp%3A%2F%2Flinked.data.gov.au%2Fdef%2Fqg-security-classifications%3E%20.%0A%20%20%7D&Accept=application/sparql-results+json). We also include something for Broader too and have a widget to display the trees.

The SPARQL query is 
`PREFIX skos:<http://www.w3.org/2004/02/skos/core#> 
SELECT *
WHERE{
  <http://linked.data.gov.au/def/qg-file-type/des-pack-types> skos:member ?concept. 
  ?concept skos:prefLabel ?prefLabel.
  OPTIONAL {?concept skos:altLabel ?Definition}.
  FILTER(LANG(?prefLabel)="en") . 
}`

We implemented a service that will harvest the query endpoint on a schedule and "cache" the data in CKAN so that we don't take a performance hit and have a degree of protection from external services being down.

The main item we need to check is that the Schemes we select on, use HTTP - pretty simple to correct but just need to be changed, tested and implemented on our end.

**Comment by nicholascar** [comment]
> Sounds like we implemented something pretty similar...

No worries: If you're happy with querying the SPARQL endpoint, that's definitely the best way to go as the SPARQL endpoint's the universal access system

**Comment by KellyVance** [comment]
I've sent a query just to be overly cautious about how our system derives its lists and relationships. It should be via our VocPrez instance rather than directly from GitHub. Once that is confirmed I'll approve this PR to get the files up-to-date (Should be this month). 

After that i'll work through the system-dependency issue to make sure everything runs smoothly when I push the changes through to VocPrez. The final push to update the live VocPrez versions may take a little more time.

**Comment by KellyVance** [comment]
@nicholascar some vocabularies seem to have not picked up the change from http to https. A lot of these had previous commits under "reversal of HTTPS for linked.data.gov.au" 05/06/2020.

borehole-design.ttl
data-access-rights.ttl
dataciteroles.ttl
depth-reference.ttl
geo-commodities.ttl
geoadmin-feature-types.ttl
geologic-feature-types.ttl
geological-observation-method.ttl
geometry-roles.ttl
geoqks.ttl
geounits.ttl
observation-detail-type.ttl
organisation-type.ttl
qld-utm-zones.ttl
sample-material.ttl
sample-relationship.ttl
sampling-method.ttl
security-classifications.ttl
seismic-dimensionality.ttl
site-status.ttl
survey-detail-type.ttl
survey-method.ttl
telephone-type.ttl

**Comment by nicholascar** [comment]
> some vocabularies seem to have not picked up the change from http to https.

Thanks @KellyVance, I've patched those vocabs with the commit above.

Also made another small commit: using dct:provenance, not dct:source, for lineage information as a literal, which fits with the Dublin Core Recommendations better and the VocPub profile

**Review by KellyVance — APPROVED** [review]

**Pull request merged**
