### PR TITLE
Update result type

### LINKED ISSUE #168: Magnetic Susceptibility missing from Units of Measure.
Hi Vance.  The units of measure seems to be missing Magnetic Susceptibility SI (unitless)

### PR DESCRIPTION
**Pull request by KellyVance**
Introduce concept of Magnetic Susceptibility as a result type.
measurement is unitless so UoM will be null/blank/not applicable/unitless.

Also rename Dog Leg Severity (industry specific) to Curvature (general)

closes #168

### CODE REVIEW

**Comment by DavidCrosswellGSQ** [comment]
> measurement is unitless so UoM will be null/blank/not applicable/unitless.
What are the permissible result values for this result type?

**Comment by Greenwoodmatthew** [comment]
@DavidCrosswellGSQ Mag sus is a ration of the magnetisation to the applied field.  common rock values are often in the 10^-5 - 10^-3 range but can be very high (iron and other para-magnetic minerals) or even negative

**Comment by KellyVance** [comment]
@Greenwoodmatthew added alternate term for capacitance/
rslt:capacitance a skos:Concept ;
    skos:altLabel "Chargeability"@en ;

**Comment by DavidCrosswellGSQ** [comment]
@Greenwoodmatthew so would the unit of measure then be ratio? or magnetism per unit volume?
Just trying to understand why there would not be a unit of measure.

**Comment by DavidCrosswellGSQ** [comment]
anyhoo - the question is unrelated to the approval of this vocab and can be answered very much later

**Comment by Greenwoodmatthew** [comment]
Thanks Vance.  I am happy with changes

**Comment by KellyVance** [comment]
Thanks @Greenwoodmatthew 
As a matter of procedure can you please: Files Changed>Review Changes>Approve>Submit Review?

**Pull request merged**
