### PR TITLE
auto-validation shapes and scripts

### PR DESCRIPTION
**Pull request by nicholascar**
Updates validation instructions, SHAPES files for validation and scripts for bulk validation. 

Only 3 small test content changes: http -> https for the publishing org in a couple of vocabs to test scripts. These are valid changes too.

### CODE REVIEW

**Review by Steven-Bowden — APPROVED** [review]
Looks good

**Review by GSQ-AI — CHANGES_REQUESTED** [review]
Looks good, but it appears that [scripts/pyshacl_bulk_**validatior**.py → validation/pyshacl_bulk_**validatior**.py] has a typo in the name?

Unless that's its actual name?

**Comment by nicholascar** [comment]
> Looks good, but it appears that [scripts/pyshacl_bulk_**validatior**.py → validation/pyshacl_bulk_**validatior**.py] has a typo in the name?
> 
> Unless that's its actual name?

Thanks for spotting that @GSQ-AI! All fixed now.

**Review by GSQ-AI — APPROVED** [review]

**Review by Steven-Bowden — APPROVED** [review]
looks good

**Pull request merged**
