### PR TITLE
Update geologic-feature-types.ttl

### PR DESCRIPTION
**Pull request by KellyVance**
Changes to [geofeatures ](https://vocabs.uat.gsq.digital/object?uri=https%3A//linked.data.gov.au/def/geofeatures/WaterBody)to support rock unit migration

**Changes**
- Moved concept scheme declaration from bottom to top (no changes to content)

- Added [Water Body](https://vocabs.uat.gsq.digital/object?uri=https%3A//linked.data.gov.au/def/geofeatures/WaterBody)

- Added Complex Rock Units subtypes
  - [Complex Igneous Rock Unit](https://vocabs.uat.gsq.digital/object?uri=https%3A//linked.data.gov.au/def/geofeatures/ComplexIgneousRockUnit)
  - [Complex Stratified Rock Unit](https://vocabs.uat.gsq.digital/object?uri=https%3A//linked.data.gov.au/def/geofeatures/ComplexStratifiedRockUnit)

### CODE REVIEW

**Review by GSQ-AI — APPROVED** [review]
Content seems to be appropriate to define the new concepts. 
Can be updated to include more detail later, if necessary.

Approved, get it in and functional, add detail later, if more is considered desireable.

**Comment by johnmckellar** [comment]
This is a tricky one and one that I had considered.

GSWA have developed a regolith classification scheme, which includes regolith mapping units, comprising in turn: landform elements, which include lakes, swamps, deltas, etc. (and also, separately(?)) deposits associated with these elements). But, their classification relates to WA and largely to the Yilgarn Craton. But, in saying this, it has also been adopted elsewhere, including overseas.

The question is: Do we classify bodies of water as regolith elements, as GSWA seemingly does, even though they are not necessarily referring to the attendant deposits? If you look at what I have compiled under 'Regolith Feature', you will see this. But the regolith-classification publications are brief and leave a lot to be desired. GSWA is currently working on further developing it. For me to say either yes or no to this PR, I would like to talk to someone in GSWA first.

Strictly speaking, surface water is not part of the regolith, but are bodies of water (apart from attendant deposits) regolith elements and therefore a regolith feature (as a regolith mapping unit)?

https://www.google.com/search?q=gswa+2007+regolith&ei=XDk1Y8fRJavo4-EPyYShiAo&ved=0ahUKEwjH75WUrrn6AhUr9DgGHUlCCKEQ4dUDCA4&uact=5&oq=gswa+2007+regolith&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEMMEEKABMggIIRDDBBCgATIICCEQwwQQoAE6CggAEB4QogQQsAM6BwgAEB4QogQ6BQgAEKIESgQIQRgBSgQIRhgAUI0LWNUkYPYlaAFwAHgAgAHVAYgBrwSSAQUwLjIuMZgBAKABAcgBAsABAQ&sclient=gws-wiz

https://www.google.com/search?q=gswa+2013+regolith&ei=XDk1Y8fRJavo4-EPyYShiAo&ved=0ahUKEwjH75WUrrn6AhUr9DgGHUlCCKEQ4dUDCA4&uact=5&oq=gswa+2013+regolith&gs_lcp=Cgdnd3Mtd2l6EAMyCggAEB4QogQQsAMyCggAEB4QogQQsANKBAhBGAFKBAhGGABQAFgAYMYJaAFwAHgAgAEAiAEAkgEAmAEAyAECwAEB&sclient=gws-wiz

**Comment by johnmckellar** [comment]
@KellyVance 
Let me get back to you tomorrow (Friday), as I have had further thoughts on this, and may go with your suggestion/request 👍

**Comment by johnmckellar** [comment]
The GSWA classification of landform elements (associated with the regolith and regolith mapping units) is far from complete.

May I therefore suggest, that under
skos:broader <http://sweetontology.net/realmGeol/GeologicFeature> ;
we introduce: ‘Landform Feature’: 

A landform is a natural physical feature of the Earth's surface largely defined by its form and location in the landscape. Examples of landforms include oceans, rivers, valleys, plateaus, mountains, plains, hills and glaciers (https://sciencing.com/common-landforms-8727172.html).

There are many definitions on the net, but the one above is concise; I like it. However, it does need further development and referencing (in terms of its authority). Some definitions do not include water bodies, but those with some authority do so.

I therefore advise that ‘Water Body’ be introduced under ‘Landform Feature’.

Thus, Water Body >>> Landform Feature >>> Geologic Feature.

This minor concept (water body) opens up a vast chasm for further development of water bodies, and a whole host of other landform features and elements. I now believe that we should go down this path, rather than dealing with such landform features as landform elements directly under Regolith Feature.

Do you agree, and, if so, do you want me to make the changes to the file?

**Comment by johnmckellar** [comment]
@KellyVance @GSQ-AI @LukeHauck @mark-gordon-dnrme 

In support of my last suggestion above, I have written the following code. I did not attempt to modify your PR (Vance), as the process would seemingly become too messy, but have provided my suggestions below, in the first instance. Note: I have modified your SKOS notation for water body.
 
    geof:LandformFeature a skos:Concept ;
    dcterms:references "After and modified from: <https://en.wikipedia.org/wiki/Landform> (accessed 05.10.22)." ;
    dcterms:references "After and modified from: <https://en.wikipedia.org/wiki/Geomorphology> (accessed 05.10.22)." ;
    dcterms:references "After and modified from: <https://sciencing.com/common-landforms-8727172.html>  (accessed 05.10.22)." ;
    dcterms:references "After and modified from: <https://examples.yourdictionary.com/examples-of-landforms.html> (accessed 05.10.22)." ;
    dcterms:references "After and modified from: <https://oceanservice.noaa.gov/facts/bathymetry.html> (accessed 05.10.22)." ;
    skos:broader <http://sweetontology.net/realmGeol/GeologicFeature> ;
    skos:related geof:RegolithLandformUnit ;
    skos:definition "Overall, any physical feature on the Earth’s surface (here excluding consideration of anthropogenic-landform features and natural-landform features on other planets) that is part of the terrain represents a landform, including: alluvial fans, braided channels, abyssal plains, atolls, beaches, cliffs, hills, mid-ocean ridges, volcanic arcs, wave-cut platforms, canyons, gullies, valleys, hoodoos, badlands, salt pans, etc., as well as all other surface bodies of water, such as rivers, lakes, marshes, glaciers and ice sheets."@en ;
    rdfs:isDefinedBy <https://linked.data.gov.au/def/geofeatures> ;
    skos:inScheme <https://linked.data.gov.au/def/geofeatures> ;
    skos:notation "gflfe" ;
    skos:prefLabel "landform feature"@en ;
    skos:scopeNote "Landforms are classified by physical attributes such as their form, location/shape, elevation, slope in the landscape (topography, bathymetry/submarine topography, respectively on land and under water), and by the processes that created them, embracing the science of geomorphology."@en .

geof:WaterBody a skos:Concept ;
    dcterms:references <https://www.usgs.gov/special-topics/water-science-school/science/freshwater-lakes-and-rivers-and-water-cycle> ;
    skos:broader geof:LandformFeature ;
    skos:definition "A feature produced by the accumulation of water at surface. These features may be liquid water in the form of lakes, rivers, and streams, or as ice in the form of ice sheets and glaciers. Considered part of the set of geologic features due to their role in geological processes and due to their intersection and coverage of other geologic features and important topographical relationships."@en ;
    rdfs:isDefinedBy <https://linked.data.gov.au/def/geofeatures> ;
    skos:inScheme <https://linked.data.gov.au/def/geofeatures> ;
    skos:notation "gflwb" ;
    skos:prefLabel "water body"@en .

**Review by LukeHauck — DISMISSED** [review]
Tech is good. A high level review of the content looks good and makes sense. Approved.

**Comment by johnmckellar** [comment]
Some changes still need to be made re complex rock units prefLabels

**Review by johnmckellar — CHANGES_REQUESTED** [review]
Line 382: From'skos:prefLabel "dominantly complex stratified rock unit"@en .' to 'skos:prefLabel "dominantly stratified complex rock unit"@en .'.

Line 391: From 'dominantly complex igneous rock unit' to 'dominantly igneous complex rock unit'

**Comment by geoderekh** [comment]
> Line 382: From'skos:prefLabel "dominantly complex stratified rock unit"@en .' to 'skos:prefLabel "dominantly stratified complex rock unit"@en .'.
> 
> Line 391: From 'dominantly complex igneous rock unit' to 'dominantly igneous complex rock unit'

I made those changes JM. They make sense in english now. 
High level content review of the vocab looks good to me.

**Review by LukeHauck — APPROVED** [review]
Re-reviewed in light of new changes. 
New changes make sense. 
Technical still good. Approved.

**Review by johnmckellar — APPROVED** [review]

**Comment by johnmckellar** [comment]
Merged

**Pull request merged**
