### PR TITLE
Update site-relationships.ttl

### PR DESCRIPTION
**Pull request by KellyVance**
adding project and temporal relationships for spatially bound entities (sites)

@LukeHauck please check with validators
@katewd please check that additions meet our needs of relating mines to mine complexes and projects.

### CODE REVIEW

**Review by LukeHauck — APPROVED** [review]
Tech good. Approved.

**Review by katewd — CHANGES_REQUESTED** [review]
I think the definitions on lines 191 and 199 (hasPart and partOf) should be swapped. Also, additions to line 251 doesn't make sense to me. Can you make this clearer?

**Comment by KellyVance** [comment]
> I think the definitions on lines 191 and 199 (hasPart and partOf) should be swapped. Also, additions to line 251 doesn't make sense to me. Can you make this clearer?

Edits made, but not sure if it is any clearer. Have included link in Concept scheme definition to direct to some visual representations of the spatial relationships.

**Review by katewd — APPROVED** [review]
Looks good to me

**Pull request merged**
