### PR TITLE
Update geologic-feature-types.ttl

### PR DESCRIPTION
**Pull request by johnmckellar**
Have updated geof, primarily to accord with rur vocab:
1. Lithodemic Feature deleted
2. Complex Rock Unit, Intrusive Rock Unit, Tectonometamorphic Rock Unit introduced
3. Tectonostratigraphic Entity changed to Tectonostratigraphic Rock Unit, with broader Tectonic Feature removed
4. Tectonic Entity deleted and merged with Tectonic Feature
5. Some rock ranks removed: suite, supersuite, etc. (from memory)
6. Igneous association 'revised'.

### CODE REVIEW

**Comment by johnmckellar** [comment]
There is a typo for solidifies. I'll fix this later.

**Comment by nicholascar** [comment]
@johnmckellar you need to put the file through the VocPub validator at http://rdftools.surroundaustralia.com/validate. When I do this I get lots of errors but they are all the same type which is:

"You _MUST NOT_ use dcterms:source property more than once on any object."

The issue here is you're interpreting the property `dcterms:source` slightly differential to how the vocabulary profile intends it four use. I think you mean `dcterms:references`, so just convert `dcterms:source` to that. 

The VocPub profile reserves `dcterms:source` for a data source that's been reinterpreted to the Concept, so that's a little different to an academic or informative source, which is what `dcterms:references` should be used for. Due to `dcterms:source` being a data source, you can see why only one per Concept is allowed.

I switched `dcterms:source` for `dcterms:references` in Rock Unit Rank similarly (see https://github.com/geological-survey-of-queensland/vocabularies/blob/master/uat-vocabularies/rock-unit-rank.ttl).

**Comment by johnmckellar** [comment]
Thanks Nick.

I did not forget your comments on rur not to use dcterms:source more than once, but did not fully comprehend about using it only once per concept and for it being reserved for a data source, as opposed to an academic source.

I ran the file through your rdf converter and corrected errors, but I did not realise that I also needed to run it through your validator.

Cheers,

John

________________________________

**Comment by johnmckellar** [comment]
When I go through the validation process, and I did try to do this before I uploaded the file, it doesn't matter which way I go, either pasting the file into the validator (Input Document) or uploading it thereto, I get the same result when I hit the validate button on the top RHS: NIL.

So, what am I doing incorrectly or not doing? I corrected the file with your rdf converter, there only being a few errors identified with this, but, as stated, I got nowhere with the validator.

________________________________

**Review by KellyVance — APPROVED** [review]
Defer detailed content review by @predam1 and @BlakePaul 
However, technically seems to be sound, and at a high level the content is logically structured and well fomed.

**Comment by KellyVance** [comment]
For this iteration or a future, can we please do our first expansion of GeoResourceAccumulation to include this hierarchy
- GeoResourceAccumulation
    - Petroleum Accumulation
        - Prospect
        - Play
        - Petroleum Field
        - Petroleum Reservoir Unit

**Comment by johnmckellar** [comment]
Sure Vance, I’ll add it to the list ☺

**Comment by johnmckellar** [comment]
Vance has reviewed this, and without waiting for other reviewers, I am merging this PR with the main.

**Pull request merged**
