### PR TITLE
Update georesources-report-types.ttl

### PR DESCRIPTION
**Pull request by talebib**
Adding missing internal report types "Any other report" and "Technical report" to the internal report collection.

### CODE REVIEW

**Comment by DavidArmstrongGSQ** [comment]
@talebib does indentation matter? Seems to be different to other lines.

**Comment by talebib** [comment]
@DavidArmstrongGSQ No idea. That's the purpose of review by experts!

**Comment by DavidArmstrongGSQ** [comment]
> @DavidArmstrongGSQ No idea. That's the purpose of review by experts!

Unfortunately that's not me, I've never seen a ttl file before! @johnmckellar  will know. John, can you please review this change by Behnam. Just making sure the formatting of a ttl file is correct. Thanks, David

**Review by johnmckellar — APPROVED** [review]
Hi Behnam @DavidArmstrongGSQ 
I take it that these concepts were included in the file, but omitted from the list here. So, all seems to be OK.
Cheers,
John

**Pull request merged**
