### PR TITLE
https updates for 3 DES vocabs

### PR DESCRIPTION
**Pull request by UbuntuScott**
updates to fix http->https.//linked.data.gov.au for 
3 DES (QESD) Catalogue vocabs:
- security-classifications, 
- qesd-unitofmeasure.ttl and 
- qesd-quantitykind.ttl

### CODE REVIEW

**Review by KellyVance — APPROVED** [review]

**Comment by KellyVance** [comment]
Let me know when approved and merged and I can update VocPrez accordingly.

**Review by UbuntuScott — COMMENTED** [review]
It  looks like it's just updating the modified date, which hopefully might fix the issues listed on the ticket and allow us to update the SPARQL queries

There may have been previous commits for http->https which didn't update the persistent URLs on the website.   

There were some http reference (in security classification and the rest), when I started this PR.   From what I recall the mod date change kicks off other processes, but agree with Nick - the files all seem to look okay in now and only seem to have only mod date updated. 

cc @broughd-qld

**Comment by UbuntuScott** [comment]
no conflicts

**Comment by UbuntuScott** [comment]
> Let me know when approved and merged and I can update VocPrez accordingly.

@KellyVance 
Merged

**Pull request merged**
