### PR TITLE
Revert all http to https migrations in PR #463

### PR DESCRIPTION
**Pull request by edmondchuc**
Revert all http to https commits in PR https://github.com/geological-survey-of-queensland/vocabularies/pull/463.

### CODE REVIEW

**Review by Steven-Bowden — APPROVED** [review]
Looks good thanks

**Comment by edmondchuc** [comment]
Tests fixed @Steven-Bowden @GSQ-AI.

**Review by Steven-Bowden — APPROVED** [review]
looks good, thanks.

**Review by LukeHauck — APPROVED** [review]
Approved.

**Review by Steven-Bowden — DISMISSED** [review]
looks fine to me

**Review by LukeHauck — APPROVED** [review]

**Review by Steven-Bowden — APPROVED** [review]
looks good thanks

**Pull request merged**
