### PR TITLE
Add unconventional petroleum geology types

### PR DESCRIPTION
**Pull request by KellyVance**
**Summary**

Added, as discussed
Basin Centred Gas Geology
Tight Oil and Gas Geology
Shale Oil and Gas Geology

For incremental change so SMEs can discuss published material that can be visualised via VocPrez to suggest further improvements. Once the hierarchy is visible in VocPrez we can seek further enhancements from wider GSQ audience.

**Reviewers**
If **[this link](https://itpqld-my.sharepoint.com/personal/vance_kelly_dnrme_qld_gov_au/Documents/Vocabulary%20Visualisations/Earth%20Science%20Data%20Category.html)** works it may help

SMEs @johnmckellar @GSQ-AI 
Tech @LukeHauck 

FYI @DavidCrosswellGSQ @lisa-woody

### CODE REVIEW

**Comment by johnmckellar** [comment]
On the note of references, how are we dealing with them? Where are we compiling them (presumably in a bibtex format)? And the thought of developing a glossary of terms is mind-boggling.

**Comment by KellyVance** [comment]
References should be in there. But i've fixed some defintion and scopeNote quotation marks so everything should display correctly.

**Comment by KellyVance** [comment]
> On the note of references, how are we dealing with them? Where are we compiling them (presumably in a bibtex format)? And the thought of developing a glossary of terms is mind-boggling.

Probably outside the bounds or requirements of pure SKOS. But one could list properly formatted full references using the dct:source prefix

**Comment by KellyVance** [comment]
> Sorry Vance, but suggest you take out the double "". Phrases are direct quotations, but entire sentences, etc are not.

triple quotes """ are a skos requirement for when definitions etc contain characters such as slashes, semi colons, or special characters. Otherwise the file doesn't read correctly

**Comment by johnmckellar** [comment]
Andrew, the scopeNote for BCG is long, representing both the complexity and ongoing evolution of the concept of it.  There are somewhat fluid views out there. I presented this info for feedback and comparison with what may be provided on the commodities side of things, and for your consequent editing. So, yes, it can be cut back, when we are satisfied with the alignment between ESDC vocab and the commodities one.

**Pull request merged**
